GET  http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order Icecream"
}

###
DELETE http://localhost:3001/todo/delete/643f9025f3c9badbb6c16bc1

###

PUT http://localhost:3001/todo/complete/643a6d7cf0c553ebd0e33254