GET  http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order Coca-Cola"
}

###
DELETE http://localhost:3001/todo/delete/643e44f4bdda9325d70f959c

###

PUT http://localhost:3001/todo/complete/643a6d7cf0c553ebd0e33254